# Generated by Django 5.1.15 on 2026-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileset",
            name="cover_letter",
            field=models.TextField(
                blank=True,
                help_text="Шаблон сопроводительного письма. Подстановки: {компания}, {должность}",
            ),
        ),
    ]
