# Generated by Django 5.1.15 on 2026-09-17 15:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="URL иконки источника", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Источник вакансий",
                "verbose_name_plural": "Источники вакансий",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("salary_from", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "₽ RUB"), ("USD", "$ USD"), ("EUR", "€ EUR")],
                        default="RUB",
                        max_length=3,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Постоянная"),
                            ("contract", "Контракт"),
                            ("freelance", "Фриланс"),
                            ("internship", "Стажировка"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior", "Junior"),
                            ("middle", "Middle"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_day", "Полный день"),
                            ("part_time", "Частичная занятость"),
                            ("remote", "Удалённо"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "required_skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "nice_to_have",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID вакансии у источника", max_length=255
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.jobsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-posted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserJobFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.PositiveIntegerField(blank=True, null=True)),
                ("max_salary", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "experience_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("junior", "Junior"),
                                ("middle", "Middle"),
                                ("senior", "Senior"),
                                ("lead", "Lead"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "excluded_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "job_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("full_time", "Постоянная"),
                                ("contract", "Контракт"),
                                ("freelance", "Фриланс"),
                                ("internship", "Стажировка"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильтр вакансий",
                "verbose_name_plural": "Фильтры вакансий",
            },
        ),
        migrations.CreateModel(
            name="JobNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to_telegram", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление о вакансии",
                "verbose_name_plural": "Уведомления о вакансиях",
                "ordering": ["-notified_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "job"), name="unique_notification_per_user_job"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["source", "-created_at"], name="jobs_job_source__ce783a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["-created_at"], name="jobs_job_created_77460a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active"], name="jobs_job_is_acti_b6ae73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["external_id"], name="jobs_job_externa_6b51f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["experience_level"], name="jobs_job_experie_09027f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_job_per_source"
            ),
        ),
    ]
