# Generated by Django 5.1.15 on 2026-09-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_favoritejob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userjobfilter",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Фильтр вакансий",
                "verbose_name_plural": "Фильтры вакансий",
            },
        ),
    ]
