# Generated by Django 5.1.15 on 2026-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_userjobfilter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("posted_at"), descending=True, nulls_last=True
                    ),
                    "-created_at",
                ],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
