# Generated by Django 5.1.15 on 2026-09-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "₽ RUB"),
                    ("USD", "$ USD"),
                    ("EUR", "€ EUR"),
                    ("UZS", "so'm UZS"),
                    ("AMD", "֏ AMD"),
                ],
                default="RUB",
                max_length=3,
            ),
        ),
    ]
